### ISSUE TITLE
 Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: Contract transaction couldn't be found after 50 blocks

### ISSUE THREAD

**Issue by faizanahmad055** [coin-worx/ethereum-voting-demo#4]
I've asked this issue [here](https://github.com/trufflesuite/truffle/issues/1074) and [here](https://github.com/trufflesuite/truffle/issues/677#issuecomment-400993173)

I'm running below mentioned command to run the ethereum node
`geth --rinkeby --syncmode "fast" --rpc --rpcapi db,eth,net,web3,personal --cache=1024 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*"`

My environment is

> Geth Version: 1.8.11-stable
> Truffle v4.1.13 (core: 4.1.13)
> Solidity v0.4.24 (solc-js)
> node version: v7.8.0
> npm version: v4.2.0

**truffle.js**
```
module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*', // Match any network id
      gas: 4712388
    },
    ropsten: {
      host: 'localhost',
      port: 8545,
      gas: 6700000,
      network_id: '3' // Match any network id
    },
    kovan: {
      host: 'localhost',
      port: 8545,
      gas: 6700000,
      network_id: '5' // Match any network id
    },
    mocha: {
      enableTimeouts: false
    }
  }
}
```

When I run truffle **migrate --reset**

it shows below error
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
```

See the full error message below

```
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x4bad5e37538025f35e48eb95d7448a910c2c9b5e7c822e9c5fd310446219f62a
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:112:1
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:128:1
    at Array.forEach (native)
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:127:1
    at Array.forEach (native)
    at Object.onMessage [as callback] (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:125:1)
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:259:1
    at Array.forEach (native)
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:258:10
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by Iamshashvat** [comment]
How do you solve this problem?
